language: php

php:
    - 7.3
    - 7.2
    - 7.1

install:
    - composer install
    - composer global require chh/bob:^1@alpha
    - export PATH=$PATH:$COMPOSER_BIN_DIR
    - bob install_dev_tools

script:
    - phpspec run
    - behat
